apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/pinnacleseven/Documents/lamp-ticket/laravel"