apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  DB_USERNAME: YWR1c2Vy
  DB_PASSWORD: YWR1c2Vy
  DB_DATABASE: bGFyYXZlbA==
  DB_HOST: "13.233.128.222"
  DB_PORT: "3306"
